"""Renders job listings and form fields as Markdown files."""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Union

from scraper.easy_apply import FormField as EasyApplyField
from scraper.external_apply import FormField as ExternalField

FormFieldUnion = Union[EasyApplyField, ExternalField]

_TYPE_LABELS = {
    "text": "Text Input",
    "textarea": "Long Text / Textarea",
    "select": "Dropdown Select",
    "radio": "Radio (Single Choice)",
    "checkbox": "Checkbox",
    "file": "File Upload",
    "unknown": "Unknown",
}

_FIELD_TYPE_ICONS = {
    "text": "✏️",
    "textarea": "📝",
    "select": "🔽",
    "radio": "🔘",
    "checkbox": "☑️",
    "file": "📎",
    "unknown": "❓",
}


def _slugify(text: str) -> str:
    text = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s-]+", "_", text).strip("_")[:60]


def _render_field_row(f: FormFieldUnion, index: int) -> str:
    icon = _FIELD_TYPE_ICONS.get(f.field_type, "❓")
    type_label = _TYPE_LABELS.get(f.field_type, f.field_type.title())
    required_badge = " `required`" if f.required else ""

    lines = [
        f"### {index}. {f.label}{required_badge}",
        f"",
        f"| Property | Value |",
        f"|----------|-------|",
        f"| **Type** | {icon} {type_label} |",
        f"| **Required** | {'Yes ✅' if f.required else 'No'} |",
    ]

    if hasattr(f, "step") and f.step:
        lines.append(f"| **Step** | {f.step} |")

    if hasattr(f, "section") and f.section:
        lines.append(f"| **Section** | {f.section} |")

    if f.placeholder:
        lines.append(f"| **Hint / Placeholder** | {f.placeholder} |")

    if f.options:
        opts_str = " · ".join(f"`{o}`" for o in f.options if o)
        lines.append(f"| **Options** | {opts_str} |")

    lines.append("")
    return "\n".join(lines)


def render_job_markdown(
    job,  # JobListing
    fields: list[FormFieldUnion],
    cfg: dict,
) -> str:
    """Return the full Markdown string for one job listing."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    app_type = "🟢 LinkedIn Easy Apply" if job.is_easy_apply else "🔵 External Application"

    lines = [
        f"# {job.title}",
        f"",
        f"> **Company:** {job.company}  ",
        f"> **Location:** {job.location or 'Not specified'}  ",
        f"> **Application Type:** {app_type}  ",
        f"> **Scraped:** {now}",
        f"",
        f"---",
        f"",
        f"## 🔗 Links",
        f"",
        f"- **LinkedIn Post:** [{job.url}]({job.url})",
    ]

    if job.external_url:
        lines.append(f"- **Application Form:** [{job.external_url}]({job.external_url})")

    lines += [
        f"",
        f"---",
        f"",
        f"## 📋 Application Form Fields",
        f"",
        f"**Total fields found:** {len(fields)}  ",
        f"**Required fields:** {sum(1 for f in fields if f.required)}",
        f"",
    ]

    if not fields:
        lines.append("> ⚠️ No form fields were extracted. The form may require JavaScript interaction or login.")
        lines.append("")
    else:
        if fields and hasattr(fields[0], "step"):
            steps: dict[int, list] = {}
            for f in fields:
                steps.setdefault(f.step, []).append(f)

            global_index = 1
            for step_num in sorted(steps):
                step_fields = steps[step_num]
                lines.append(f"### 📄 Step {step_num}")
                lines.append("")
                for f in step_fields:
                    lines.append(_render_field_row(f, global_index))
                    global_index += 1
        else:
            sections: dict[str, list] = {}
            for f in fields:
                sec = getattr(f, "section", "") or "General"
                sections.setdefault(sec, []).append(f)

            global_index = 1
            for sec_name, sec_fields in sections.items():
                if sec_name and sec_name != "General":
                    lines.append(f"### 📂 {sec_name}")
                    lines.append("")
                for f in sec_fields:
                    lines.append(_render_field_row(f, global_index))
                    global_index += 1

    lines += [
        "---",
        "",
        f"*Generated by LinkedIn Job Scraper · {now}*",
        "",
    ]

    return "\n".join(lines)


def save_job_markdown(
    job,
    fields: list[FormFieldUnion],
    cfg: dict,
) -> Path:
    """Write the rendered markdown to a file and return the path."""
    output_dir = Path(cfg["output"]["dir"])
    output_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{_slugify(job.title)}_{_slugify(job.company)}.md"
    filepath = output_dir / filename

    content = render_job_markdown(job, fields, cfg)
    filepath.write_text(content, encoding="utf-8")

    return filepath


def save_summary_markdown(
    all_jobs: list[tuple],
    cfg: dict,
) -> Path:
    """Write a single summary file with all jobs and their fields."""
    output_dir = Path(cfg["output"]["dir"])
    output_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# LinkedIn Job Scraper — Summary",
        f"",
        f"**Generated:** {now}  ",
        f"**Total jobs:** {len(all_jobs)}",
        f"",
        f"---",
        f"",
    ]

    for job, fields, _ in all_jobs:
        lines.append(render_job_markdown(job, fields, cfg))
        lines.append("\n---\n")

    filepath = output_dir / "summary.md"
    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filepath
